# Generated by Django 5.2.8 on 2025-12-07 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.meal')),
                ('Table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.table')),
            ],
        ),
    ]
