# Generated by Django 5.2.8 on 2025-12-08 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_yourorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'во готово'), ('card', 'Со каратичка')], max_length=10, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.table')),
            ],
        ),
    ]
