# Generated by Django 5.2.8 on 2025-11-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='titleMK',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='descriptionMK',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='priceMK',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='titleMK',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
